### ISSUE TITLE
Question about implementing details on video gligen

### ISSUE THREAD

**Issue by DongGeun-Yoon** [TonyLianLong/igligen#3]
Thank you for sharing your work.

Inspired by LVD, I am trying to train Image2Video model. I have a few questions I would like to ask:

- How to organize the video data for training?
- How to train the video gligen (ModelScope)? Is it sufficient to use the pretrained weights and modify the gated type, or are there other tactics I should consider?
- I am also interested in the detailed training settings, such as iterations, GPU configuration, and so on.

**Comment by TonyLianLong** [comment]
Perhaps surprisingly, the gligen adapters of ModelScope is trained without videos. This is supported by the release code (as I use this code to train the released ModelScope GLIGEN adapters). This is how I did it:

First note that ModelScope is just SDv2.1 with temporal layers. If you remove the temporal layers, you get weights in the structure of SDv2.1 (but the weights are not exactly the same as SDv2.1). Therefore, we first remove the temporal layers of ModelScope, and train it just like we train GLIGEN adapters for SDv2.1. Then, we put the adapters back to ModelScope weights (with the temporal part). Since diffusers video UNet doesn't support gligen, you need to modify video UNet architecture which adds support of GLIGEN adapters (they are in python files in [our released ModelScope + gligen HF models](https://huggingface.co/longlian/text-to-video-lvd-ms), feel free to use them in your project but please put a reference to us). The training setting is exactly the same as how I train for SDv2.1 (which is in the config). However, feel free to explore more options.

It's possible to use video supervision and get better control coherency in the trained GLIGEN adapters (as the adapters are trained with full ModelScope). However, this takes a lot of compute. Since gligen is just for control, I believe training with image-level (frame-level) supervision is much more efficient.

This also applies to ZeroScope, except that you need to get images that are not square. It is also trained with this code.
